/**
 * AWS SES Service - Direct AWS SDK Integration
 * 
 * This service provides AWS SES email sending capabilities with:
 * - Error handling and logging
 * - HTML and text email bodies
 * - CC/BCC support
 * - Reply-to addresses
 * - Tags for email tracking
 */

import { SESClient, SendEmailCommand } from '@aws-sdk/client-ses';

// Initialize AWS SES Client
let sesClient = null;

/**
 * Initialize SES client with environment variables
 */
const initializeSESClient = () => {
  if (sesClient) {
    return sesClient;
  }

  const region = import.meta.env.VITE_AWS_SES_REGION || 'us-east-1';
  const accessKeyId = import.meta.env.VITE_AWS_ACCESS_KEY_ID;
  const secretAccessKey = import.meta.env.VITE_AWS_SECRET_ACCESS_KEY;

  if (!accessKeyId || !secretAccessKey) {
    console.warn('⚠️  AWS credentials not configured. Email sending will be simulated.');
    return null;
  }

  try {
    sesClient = new SESClient({
      region,
      credentials: {
        accessKeyId,
        secretAccessKey,
      },
    });
    console.log('✅ AWS SES Client initialized successfully');
    return sesClient;
  } catch (error) {
    console.error('❌ Failed to initialize AWS SES Client:', error);
    return null;
  }
};

/**
 * Send email using AWS SES
 * 
 * SECURITY NOTE: This function is designed to send controlled email templates
 * generated by emailTemplates.js. All HTML content passed to this function
 * should be from trusted, controlled templates - never from unsanitized user input.
 * 
 * @param {Object} emailParams - Email parameters
 * @param {string} emailParams.to - Recipient email address
 * @param {string} emailParams.subject - Email subject
 * @param {string} emailParams.htmlBody - HTML email body (from controlled templates)
 * @param {string} emailParams.textBody - Plain text email body (optional)
 * @param {string[]} emailParams.cc - CC email addresses (optional)
 * @param {string[]} emailParams.bcc - BCC email addresses (optional)
 * @param {string} emailParams.replyTo - Reply-to email address (optional)
 * @param {Object} emailParams.tags - Email tags for tracking (optional)
 * @returns {Promise<Object>} - Result object with success status and message ID
 */
export const sendEmail = async (emailParams) => {
  const {
    to,
    subject,
    htmlBody,
    textBody = '',
    cc = [],
    bcc = [],
    replyTo = import.meta.env.VITE_AWS_SES_REPLY_TO || 'support@swift-verify.org',
    tags = {},
  } = emailParams;

  const fromEmail = import.meta.env.VITE_AWS_SES_FROM_EMAIL || 'noreply@swift-verify.org';

  console.log('📧 Preparing to send email via AWS SES');
  console.log('To:', to);
  console.log('Subject:', subject);
  console.log('From:', fromEmail);
  console.log('Reply-To:', replyTo);

  // Initialize client
  const client = initializeSESClient();

  // If no client (no credentials), simulate email sending
  if (!client) {
    console.log('🔄 Simulating email send (no AWS credentials configured)');
    console.log('Email content:', { to, subject, htmlBody: htmlBody.substring(0, 100) + '...' });
    
    // Simulate delay
    await new Promise(resolve => setTimeout(resolve, 500));
    
    return {
      success: true,
      messageId: `sim_${Date.now()}`,
      message: 'Email simulated successfully (no AWS credentials)',
    };
  }

  try {
    // Prepare SES email command
    const params = {
      Source: fromEmail,
      Destination: {
        ToAddresses: Array.isArray(to) ? to : [to],
        CcAddresses: cc,
        BccAddresses: bcc,
      },
      Message: {
        Subject: {
          Data: subject,
          Charset: 'UTF-8',
        },
        Body: {
          Html: {
            Data: htmlBody,
            Charset: 'UTF-8',
          },
          Text: {
            // Fallback: strip HTML tags if no plain text version provided
            // This processes controlled email template HTML, not user input
            Data: textBody || htmlBody.replace(/<[^>]+>/g, ''),
            Charset: 'UTF-8',
          },
        },
      },
      ReplyToAddresses: [replyTo],
    };

    // Add tags if provided
    if (Object.keys(tags).length > 0) {
      params.Tags = Object.entries(tags).map(([key, value]) => ({
        Name: key,
        Value: String(value),
      }));
    }

    // Send email
    const command = new SendEmailCommand(params);
    const response = await client.send(command);

    console.log('✅ Email sent successfully via AWS SES');
    console.log('Message ID:', response.MessageId);

    return {
      success: true,
      messageId: response.MessageId,
      message: 'Email sent successfully',
    };
  } catch (error) {
    console.error('❌ Failed to send email via AWS SES:', error);
    
    // Handle specific AWS SES errors
    if (error.name === 'MessageRejected') {
      return {
        success: false,
        error: 'Email was rejected by AWS SES',
        details: error.message,
      };
    } else if (error.name === 'MailFromDomainNotVerifiedException') {
      return {
        success: false,
        error: 'Sender email domain not verified in AWS SES',
        details: 'Please verify your domain in AWS SES console',
      };
    } else if (error.name === 'ConfigurationSetDoesNotExistException') {
      return {
        success: false,
        error: 'AWS SES configuration set not found',
        details: error.message,
      };
    }

    return {
      success: false,
      error: 'Failed to send email',
      details: error.message,
    };
  }
};

/**
 * Send templated email with retry logic
 * 
 * @param {Object} emailParams - Email parameters
 * @param {number} retries - Number of retry attempts (default: 3)
 * @returns {Promise<Object>} - Result object
 */
export const sendEmailWithRetry = async (emailParams, retries = 3) => {
  let lastError = null;

  for (let attempt = 1; attempt <= retries; attempt++) {
    console.log(`📧 Email send attempt ${attempt}/${retries}`);
    
    try {
      const result = await sendEmail(emailParams);
      
      if (result.success) {
        return result;
      }
      
      lastError = result;
      
      // Don't retry on certain errors
      if (result.error && result.error.includes('rejected')) {
        console.error('Email rejected, not retrying');
        return result;
      }
      
      // Wait before retry (exponential backoff)
      if (attempt < retries) {
        const delay = Math.pow(2, attempt) * 1000; // 2s, 4s, 8s
        console.log(`⏳ Waiting ${delay/1000}s before retry...`);
        await new Promise(resolve => setTimeout(resolve, delay));
      }
    } catch (error) {
      lastError = { success: false, error: error.message };
      
      if (attempt < retries) {
        const delay = Math.pow(2, attempt) * 1000;
        console.log(`⏳ Waiting ${delay/1000}s before retry...`);
        await new Promise(resolve => setTimeout(resolve, delay));
      }
    }
  }

  console.error(`❌ All ${retries} email send attempts failed`);
  return lastError || { success: false, error: 'All retry attempts failed' };
};

export default {
  sendEmail,
  sendEmailWithRetry,
};
